# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '10.0'
use_frameworks!


target 'piscine_rush01' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks



  # Pods for piscine_rush01
  pod 'Mapbox-iOS-SDK', '~> 3.5'
  pod 'MapboxDirections.swift', '~> 0.9'
  pod 'MapboxStatic.swift', '~> 0.9'
  pod 'MapboxGeocoder.swift', '~> 0.6'
  pod 'MapboxNavigation', '~> 0.4.0'

  target 'piscine_rush01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'piscine_rush01UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
